package cn.com.xinchantou.light.model;

import java.util.Date;

public class LtUreportFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.report_code
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private Integer reportCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.report_name
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private String reportName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.remarks
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.create_date
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.create_by
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.update_date
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.update_by
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lt_ureport_file.content
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.report_code
     *
     * @return the value of lt_ureport_file.report_code
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public Integer getReportCode() {
        return reportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.report_code
     *
     * @param reportCode the value for lt_ureport_file.report_code
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setReportCode(Integer reportCode) {
        this.reportCode = reportCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.report_name
     *
     * @return the value of lt_ureport_file.report_name
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public String getReportName() {
        return reportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.report_name
     *
     * @param reportName the value for lt_ureport_file.report_name
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setReportName(String reportName) {
        this.reportName = reportName == null ? null : reportName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.remarks
     *
     * @return the value of lt_ureport_file.remarks
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.remarks
     *
     * @param remarks the value for lt_ureport_file.remarks
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.create_date
     *
     * @return the value of lt_ureport_file.create_date
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.create_date
     *
     * @param createDate the value for lt_ureport_file.create_date
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.create_by
     *
     * @return the value of lt_ureport_file.create_by
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.create_by
     *
     * @param createBy the value for lt_ureport_file.create_by
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.update_date
     *
     * @return the value of lt_ureport_file.update_date
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.update_date
     *
     * @param updateDate the value for lt_ureport_file.update_date
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.update_by
     *
     * @return the value of lt_ureport_file.update_by
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.update_by
     *
     * @param updateBy the value for lt_ureport_file.update_by
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lt_ureport_file.content
     *
     * @return the value of lt_ureport_file.content
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lt_ureport_file.content
     *
     * @param content the value for lt_ureport_file.content
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}