package cn.com.xinchantou.light.mapper;


import cn.com.xinchantou.light.model.LtUreportFile;

import java.util.List;

public interface LtUreportFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ureport_file
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    int deleteByPrimaryKey(Integer reportCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ureport_file
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    int insert(LtUreportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ureport_file
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    int insertSelective(LtUreportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ureport_file
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    LtUreportFile selectByPrimaryKey(Integer reportCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ureport_file
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    int updateByPrimaryKeySelective(LtUreportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ureport_file
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(LtUreportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lt_ureport_file
     *
     * @mbg.generated Thu Oct 17 16:53:48 CST 2019
     */
    int updateByPrimaryKey(LtUreportFile record);

    /**
     *  根据报表名称检查报表是否存在
     * @param name 报表名称
     * @return
     */
    int checkExistByName(String reportName);

    /**
     *  根据报表名称查询报表
     * @param reportName 报表名称
     * @return
     */
    LtUreportFile selectByName(String reportName);

    /**
     * 查询全部报表
     * @return
     */
    List<LtUreportFile> queryReportFileList();

    /**
     * 根据报表名称删除报表
     * @param name
     * @return
     */
    int deleteReportFileByName(String name);

}